/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:21 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

/*
 * For Table alumno
 */
public class Alumno implements java.io.Serializable, Cloneable {
    private AlumnoKey _key = new AlumnoKey();

    /* boleta, PK */
    protected String boleta;

    /* nombreAlumno */
    protected String nombrealumno;

    /* paternoAlumno */
    protected String paternoalumno;

    /* maternoAlumno */
    protected String maternoalumno;

    /* fechaNacimiento */
    protected java.util.Date fechanacimiento;

    /* calle */
    protected String calle;

    /* colonia */
    protected String colonia;

    /* numero */
    protected int numero;

    /* codigoPostal */
    protected long codigopostal;

    /* sexo */
    protected String sexo;

    /* correo */
    protected String correo;

    /* idcarrera */
    protected int idcarrera;

    /* Return the key object. */
    public AlumnoKey getKeyObject() {
        return _key;
    }

    /* boleta, PK */
    public String getBoleta() {
        return boleta;
    }

    /* boleta, PK */
    public void setBoleta(String boleta) {
        this.boleta = boleta;
        _key.setBoleta(boleta);
    }

    /* nombreAlumno */
    public String getNombrealumno() {
        return nombrealumno;
    }

    /* nombreAlumno */
    public void setNombrealumno(String nombrealumno) {
        this.nombrealumno = nombrealumno;
    }

    /* paternoAlumno */
    public String getPaternoalumno() {
        return paternoalumno;
    }

    /* paternoAlumno */
    public void setPaternoalumno(String paternoalumno) {
        this.paternoalumno = paternoalumno;
    }

    /* maternoAlumno */
    public String getMaternoalumno() {
        return maternoalumno;
    }

    /* maternoAlumno */
    public void setMaternoalumno(String maternoalumno) {
        this.maternoalumno = maternoalumno;
    }

    /* fechaNacimiento */
    public java.util.Date getFechanacimiento() {
        return fechanacimiento;
    }

    /* fechaNacimiento */
    public void setFechanacimiento(java.util.Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }

    /* calle */
    public String getCalle() {
        return calle;
    }

    /* calle */
    public void setCalle(String calle) {
        this.calle = calle;
    }

    /* colonia */
    public String getColonia() {
        return colonia;
    }

    /* colonia */
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }

    /* numero */
    public int getNumero() {
        return numero;
    }

    /* numero */
    public void setNumero(int numero) {
        this.numero = numero;
    }

    /* codigoPostal */
    public long getCodigopostal() {
        return codigopostal;
    }

    /* codigoPostal */
    public void setCodigopostal(long codigopostal) {
        this.codigopostal = codigopostal;
    }

    /* sexo */
    public String getSexo() {
        return sexo;
    }

    /* sexo */
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    /* correo */
    public String getCorreo() {
        return correo;
    }

    /* correo */
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    /* idcarrera */
    public int getIdcarrera() {
        return idcarrera;
    }

    /* idcarrera */
    public void setIdcarrera(int idcarrera) {
        this.idcarrera = idcarrera;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Alumno))
            return false;

        Alumno bean = (Alumno) obj;

        if (this.boleta == null) {
            if (bean.boleta != null)
                return false;
        }
        else if (!this.boleta.equals(bean.boleta)) 
            return false;

        if (this.nombrealumno == null) {
            if (bean.nombrealumno != null)
                return false;
        }
        else if (!this.nombrealumno.equals(bean.nombrealumno)) 
            return false;

        if (this.paternoalumno == null) {
            if (bean.paternoalumno != null)
                return false;
        }
        else if (!this.paternoalumno.equals(bean.paternoalumno)) 
            return false;

        if (this.maternoalumno == null) {
            if (bean.maternoalumno != null)
                return false;
        }
        else if (!this.maternoalumno.equals(bean.maternoalumno)) 
            return false;

        if (this.fechanacimiento == null) {
            if (bean.fechanacimiento != null)
                return false;
        }
        else if (!this.fechanacimiento.equals(bean.fechanacimiento)) 
            return false;

        if (this.calle == null) {
            if (bean.calle != null)
                return false;
        }
        else if (!this.calle.equals(bean.calle)) 
            return false;

        if (this.colonia == null) {
            if (bean.colonia != null)
                return false;
        }
        else if (!this.colonia.equals(bean.colonia)) 
            return false;

        if (this.numero != bean.numero)
            return false;

        if (this.codigopostal != bean.codigopostal)
            return false;

        if (this.sexo == null) {
            if (bean.sexo != null)
                return false;
        }
        else if (!this.sexo.equals(bean.sexo)) 
            return false;

        if (this.correo == null) {
            if (bean.correo != null)
                return false;
        }
        else if (!this.correo.equals(bean.correo)) 
            return false;

        if (this.idcarrera != bean.idcarrera)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Alumno bean = new Alumno();
        bean.boleta = this.boleta;
        bean.nombrealumno = this.nombrealumno;
        bean.paternoalumno = this.paternoalumno;
        bean.maternoalumno = this.maternoalumno;
        if (this.fechanacimiento != null)
            bean.fechanacimiento = (java.util.Date) this.fechanacimiento.clone();
        bean.calle = this.calle;
        bean.colonia = this.colonia;
        bean.numero = this.numero;
        bean.codigopostal = this.codigopostal;
        bean.sexo = this.sexo;
        bean.correo = this.correo;
        bean.idcarrera = this.idcarrera;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("boleta").append(" = ").append(boleta).append("]").append(sep);
        sb.append("[").append("nombrealumno").append(" = ").append(nombrealumno).append("]").append(sep);
        sb.append("[").append("paternoalumno").append(" = ").append(paternoalumno).append("]").append(sep);
        sb.append("[").append("maternoalumno").append(" = ").append(maternoalumno).append("]").append(sep);
        sb.append("[").append("fechanacimiento").append(" = ").append(fechanacimiento).append("]").append(sep);
        sb.append("[").append("calle").append(" = ").append(calle).append("]").append(sep);
        sb.append("[").append("colonia").append(" = ").append(colonia).append("]").append(sep);
        sb.append("[").append("numero").append(" = ").append(numero).append("]").append(sep);
        sb.append("[").append("codigopostal").append(" = ").append(codigopostal).append("]").append(sep);
        sb.append("[").append("sexo").append(" = ").append(sexo).append("]").append(sep);
        sb.append("[").append("correo").append(" = ").append(correo).append("]").append(sep);
        sb.append("[").append("idcarrera").append(" = ").append(idcarrera).append("]").append(sep);
        return sb.toString();
    }
}