/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:21 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

public class AlumnoKey implements java.io.Serializable, Cloneable {
    /* boleta */
    protected String boleta;

    /* boleta */
    public String getBoleta() {
        return boleta;
    }

    /* boleta */
    public void setBoleta(String boleta) {
        this.boleta = boleta;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (boleta != null)  
            hashCode += boleta.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof AlumnoKey))
            return false;

        AlumnoKey key = (AlumnoKey) obj;

        if (this.boleta == null) {
            if (key.boleta != null)
                return false;
        }
        else if (!this.boleta.equals(key.boleta)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        AlumnoKey key = new AlumnoKey();
        key.boleta = this.boleta;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("boleta").append(" = ").append(boleta).append("]");
        return sb.toString();
    }
}