/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:36 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

/*
 * For Table calificacion
 */
public class Calificacion implements java.io.Serializable, Cloneable {
    private CalificacionKey _key = new CalificacionKey();

    /* idcalificacion, PK */
    protected int idcalificacion;

    /* puntaje */
    protected double puntaje;

    /* boleta */
    protected String boleta;

    /* idexamen */
    protected int idexamen;

    /* Return the key object. */
    public CalificacionKey getKeyObject() {
        return _key;
    }

    /* idcalificacion, PK */
    public int getIdcalificacion() {
        return idcalificacion;
    }

    /* idcalificacion, PK */
    public void setIdcalificacion(int idcalificacion) {
        this.idcalificacion = idcalificacion;
        _key.setIdcalificacion(idcalificacion);
    }

    /* puntaje */
    public double getPuntaje() {
        return puntaje;
    }

    /* puntaje */
    public void setPuntaje(double puntaje) {
        this.puntaje = puntaje;
    }

    /* boleta */
    public String getBoleta() {
        return boleta;
    }

    /* boleta */
    public void setBoleta(String boleta) {
        this.boleta = boleta;
    }

    /* idexamen */
    public int getIdexamen() {
        return idexamen;
    }

    /* idexamen */
    public void setIdexamen(int idexamen) {
        this.idexamen = idexamen;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Calificacion))
            return false;

        Calificacion bean = (Calificacion) obj;

        if (this.idcalificacion != bean.idcalificacion)
            return false;

        if (this.puntaje != bean.puntaje)
            return false;

        if (this.boleta == null) {
            if (bean.boleta != null)
                return false;
        }
        else if (!this.boleta.equals(bean.boleta)) 
            return false;

        if (this.idexamen != bean.idexamen)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Calificacion bean = new Calificacion();
        bean.idcalificacion = this.idcalificacion;
        bean.puntaje = this.puntaje;
        bean.boleta = this.boleta;
        bean.idexamen = this.idexamen;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcalificacion").append(" = ").append(idcalificacion).append("]").append(sep);
        sb.append("[").append("puntaje").append(" = ").append(puntaje).append("]").append(sep);
        sb.append("[").append("boleta").append(" = ").append(boleta).append("]").append(sep);
        sb.append("[").append("idexamen").append(" = ").append(idexamen).append("]").append(sep);
        return sb.toString();
    }
}