/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:36 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

public class CalificacionKey implements java.io.Serializable, Cloneable {
    /* idcalificacion */
    protected int idcalificacion;

    /* idcalificacion */
    public int getIdcalificacion() {
        return idcalificacion;
    }

    /* idcalificacion */
    public void setIdcalificacion(int idcalificacion) {
        this.idcalificacion = idcalificacion;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idcalificacion).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CalificacionKey))
            return false;

        CalificacionKey key = (CalificacionKey) obj;

        if (this.idcalificacion != key.idcalificacion)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        CalificacionKey key = new CalificacionKey();
        key.idcalificacion = this.idcalificacion;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcalificacion").append(" = ").append(idcalificacion).append("]");
        return sb.toString();
    }
}