/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:36 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

public class CarreraKey implements java.io.Serializable, Cloneable {
    /* idcarrera */
    protected int idcarrera;

    /* idcarrera */
    public int getIdcarrera() {
        return idcarrera;
    }

    /* idcarrera */
    public void setIdcarrera(int idcarrera) {
        this.idcarrera = idcarrera;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idcarrera).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof CarreraKey))
            return false;

        CarreraKey key = (CarreraKey) obj;

        if (this.idcarrera != key.idcarrera)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        CarreraKey key = new CarreraKey();
        key.idcarrera = this.idcarrera;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcarrera").append(" = ").append(idcarrera).append("]");
        return sb.toString();
    }
}