/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:36 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

/*
 * For Table carrera
 */
public class Carrera implements java.io.Serializable, Cloneable {
    private CarreraKey _key = new CarreraKey();

    /* idcarrera, PK */
    protected int idcarrera;

    /* nombreCarrera */
    protected String nombrecarrera;

    /* duracion */
    protected int duracion;

    /* Return the key object. */
    public CarreraKey getKeyObject() {
        return _key;
    }

    /* idcarrera, PK */
    public int getIdcarrera() {
        return idcarrera;
    }

    /* idcarrera, PK */
    public void setIdcarrera(int idcarrera) {
        this.idcarrera = idcarrera;
        _key.setIdcarrera(idcarrera);
    }

    /* nombreCarrera */
    public String getNombrecarrera() {
        return nombrecarrera;
    }

    /* nombreCarrera */
    public void setNombrecarrera(String nombrecarrera) {
        this.nombrecarrera = nombrecarrera;
    }

    /* duracion */
    public int getDuracion() {
        return duracion;
    }

    /* duracion */
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Carrera))
            return false;

        Carrera bean = (Carrera) obj;

        if (this.idcarrera != bean.idcarrera)
            return false;

        if (this.nombrecarrera == null) {
            if (bean.nombrecarrera != null)
                return false;
        }
        else if (!this.nombrecarrera.equals(bean.nombrecarrera)) 
            return false;

        if (this.duracion != bean.duracion)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Carrera bean = new Carrera();
        bean.idcarrera = this.idcarrera;
        bean.nombrecarrera = this.nombrecarrera;
        bean.duracion = this.duracion;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idcarrera").append(" = ").append(idcarrera).append("]").append(sep);
        sb.append("[").append("nombrecarrera").append(" = ").append(nombrecarrera).append("]").append(sep);
        sb.append("[").append("duracion").append(" = ").append(duracion).append("]").append(sep);
        return sb.toString();
    }
}