/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:36 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

/*
 * For Table materia
 */
public class Materia implements java.io.Serializable, Cloneable {
    private MateriaKey _key = new MateriaKey();

    /* idmateria, PK */
    protected int idmateria;

    /* nombreMateria */
    protected String nombremateria;

    /* creditos */
    protected int creditos;

    /* Return the key object. */
    public MateriaKey getKeyObject() {
        return _key;
    }

    /* idmateria, PK */
    public int getIdmateria() {
        return idmateria;
    }

    /* idmateria, PK */
    public void setIdmateria(int idmateria) {
        this.idmateria = idmateria;
        _key.setIdmateria(idmateria);
    }

    /* nombreMateria */
    public String getNombremateria() {
        return nombremateria;
    }

    /* nombreMateria */
    public void setNombremateria(String nombremateria) {
        this.nombremateria = nombremateria;
    }

    /* creditos */
    public int getCreditos() {
        return creditos;
    }

    /* creditos */
    public void setCreditos(int creditos) {
        this.creditos = creditos;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Materia))
            return false;

        Materia bean = (Materia) obj;

        if (this.idmateria != bean.idmateria)
            return false;

        if (this.nombremateria == null) {
            if (bean.nombremateria != null)
                return false;
        }
        else if (!this.nombremateria.equals(bean.nombremateria)) 
            return false;

        if (this.creditos != bean.creditos)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Materia bean = new Materia();
        bean.idmateria = this.idmateria;
        bean.nombremateria = this.nombremateria;
        bean.creditos = this.creditos;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idmateria").append(" = ").append(idmateria).append("]").append(sep);
        sb.append("[").append("nombremateria").append(" = ").append(nombremateria).append("]").append(sep);
        sb.append("[").append("creditos").append(" = ").append(creditos).append("]").append(sep);
        return sb.toString();
    }
}