/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:36 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

public class PreguntaKey implements java.io.Serializable, Cloneable {
    /* idpregunta */
    protected int idpregunta;

    /* idpregunta */
    public int getIdpregunta() {
        return idpregunta;
    }

    /* idpregunta */
    public void setIdpregunta(int idpregunta) {
        this.idpregunta = idpregunta;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idpregunta).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof PreguntaKey))
            return false;

        PreguntaKey key = (PreguntaKey) obj;

        if (this.idpregunta != key.idpregunta)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        PreguntaKey key = new PreguntaKey();
        key.idpregunta = this.idpregunta;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idpregunta").append(" = ").append(idpregunta).append("]");
        return sb.toString();
    }
}