/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:37 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

/*
 * For Table profesor
 */
public class Profesor implements java.io.Serializable, Cloneable {
    private ProfesorKey _key = new ProfesorKey();

    /* numProfesor, PK */
    protected String numprofesor;

    /* correo */
    protected String correo;

    /* Return the key object. */
    public ProfesorKey getKeyObject() {
        return _key;
    }

    /* numProfesor, PK */
    public String getNumprofesor() {
        return numprofesor;
    }

    /* numProfesor, PK */
    public void setNumprofesor(String numprofesor) {
        this.numprofesor = numprofesor;
        _key.setNumprofesor(numprofesor);
    }

    /* correo */
    public String getCorreo() {
        return correo;
    }

    /* correo */
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Profesor))
            return false;

        Profesor bean = (Profesor) obj;

        if (this.numprofesor == null) {
            if (bean.numprofesor != null)
                return false;
        }
        else if (!this.numprofesor.equals(bean.numprofesor)) 
            return false;

        if (this.correo == null) {
            if (bean.correo != null)
                return false;
        }
        else if (!this.correo.equals(bean.correo)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Profesor bean = new Profesor();
        bean.numprofesor = this.numprofesor;
        bean.correo = this.correo;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("numprofesor").append(" = ").append(numprofesor).append("]").append(sep);
        sb.append("[").append("correo").append(" = ").append(correo).append("]").append(sep);
        return sb.toString();
    }
}