/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:37 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

public class ProfesorKey implements java.io.Serializable, Cloneable {
    /* numProfesor */
    protected String numprofesor;

    /* numProfesor */
    public String getNumprofesor() {
        return numprofesor;
    }

    /* numProfesor */
    public void setNumprofesor(String numprofesor) {
        this.numprofesor = numprofesor;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (numprofesor != null)  
            hashCode += numprofesor.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof ProfesorKey))
            return false;

        ProfesorKey key = (ProfesorKey) obj;

        if (this.numprofesor == null) {
            if (key.numprofesor != null)
                return false;
        }
        else if (!this.numprofesor.equals(key.numprofesor)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        ProfesorKey key = new ProfesorKey();
        key.numprofesor = this.numprofesor;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("numprofesor").append(" = ").append(numprofesor).append("]");
        return sb.toString();
    }
}