/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:37 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dto;

/*
 * For Table respuesta
 */
public class Respuesta implements java.io.Serializable, Cloneable {
    private RespuestaKey _key = new RespuestaKey();

    /* idrespuesta, PK */
    protected int idrespuesta;

    /* respuesta */
    protected String respuesta;

    /* idpregunta */
    protected int idpregunta;

    /* Return the key object. */
    public RespuestaKey getKeyObject() {
        return _key;
    }

    /* idrespuesta, PK */
    public int getIdrespuesta() {
        return idrespuesta;
    }

    /* idrespuesta, PK */
    public void setIdrespuesta(int idrespuesta) {
        this.idrespuesta = idrespuesta;
        _key.setIdrespuesta(idrespuesta);
    }

    /* respuesta */
    public String getRespuesta() {
        return respuesta;
    }

    /* respuesta */
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }

    /* idpregunta */
    public int getIdpregunta() {
        return idpregunta;
    }

    /* idpregunta */
    public void setIdpregunta(int idpregunta) {
        this.idpregunta = idpregunta;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Respuesta))
            return false;

        Respuesta bean = (Respuesta) obj;

        if (this.idrespuesta != bean.idrespuesta)
            return false;

        if (this.respuesta == null) {
            if (bean.respuesta != null)
                return false;
        }
        else if (!this.respuesta.equals(bean.respuesta)) 
            return false;

        if (this.idpregunta != bean.idpregunta)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Respuesta bean = new Respuesta();
        bean.idrespuesta = this.idrespuesta;
        bean.respuesta = this.respuesta;
        bean.idpregunta = this.idpregunta;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idrespuesta").append(" = ").append(idrespuesta).append("]").append(sep);
        sb.append("[").append("respuesta").append(" = ").append(respuesta).append("]").append(sep);
        sb.append("[").append("idpregunta").append(" = ").append(idpregunta).append("]").append(sep);
        return sb.toString();
    }
}