/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Sep 16 16:53:36 CDT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.escom.wad.prac1.dao;

import java.sql.Connection;
import java.sql.SQLException;
import com.escom.wad.prac1.dto.Pregunta;
import com.escom.wad.prac1.dto.PreguntaKey;

/**
 * This interface provides methods to populate DB Table of pregunta
 */
public interface PreguntaDAO {
    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Pregunta bean, Connection conn) throws SQLException;

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Pregunta load(PreguntaKey key, Connection conn) throws SQLException;

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Pregunta bean, Connection conn) throws SQLException;

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(PreguntaKey key, Connection conn) throws SQLException;
}